import type { PillarData } from "@/lib/content/pillar-types"
import { data as p0 } from "./barat-traditions-pakistani-wedding-guide"
import { data as p1 } from "./best-time-to-get-married-in-pakistan"
import { data as p2 } from "./destination-weddings-in-pakistan"
import { data as p3 } from "./groom-sherwani-guide-pakistan"
import { data as p4 } from "./how-to-choose-a-wedding-caterer-in-pakistan"
import { data as p5 } from "./how-to-choose-a-wedding-photographer-in-pakistan"
import { data as p6 } from "./how-to-choose-a-wedding-venue-in-pakistan"
import { data as p7 } from "./how-to-plan-a-mehndi-function"
import { data as p8 } from "./how-to-plan-a-wedding-in-pakistan"
import { data as p9 } from "./mayun-and-dholki-guide-pakistan"
import { data as p10 } from "./nikah-process-in-pakistan"
import { data as p11 } from "./pakistani-wedding-events-order"
import { data as p12 } from "./pakistani-wedding-invitation-wording"
import { data as p13 } from "./wedding-catering-menu-guide-pakistan"
import { data as p14 } from "./what-is-walima-pakistani-wedding-guide"
import { data as p15 } from "./what-to-wear-to-a-pakistani-wedding-guest-guide"

/** All data-driven content pillars (for sitemap + listings). */
export const CONTENT_PILLARS: PillarData[] = [p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15]
