import { SITE_URL } from "@/lib/seo"

/**
 * Sitemap index — points search engines at every shard generated by
 * `app/sitemap.ts`'s `generateSitemaps()` call.
 *
 * Background: Next.js 14.2 with `generateSitemaps` writes one file per
 * shard (`/sitemap/0.xml`, `/sitemap/1.xml`, ...) but does NOT
 * auto-generate an index at `/sitemap.xml`. Without this route, GSC
 * receives a 404 when crawlers (or you) submit `weddingwala.pk/sitemap.xml`.
 *
 * Per https://www.sitemaps.org/protocol.html#index, an index file is just
 * a `<sitemapindex>` document listing each shard's `<loc>` and optional
 * `<lastmod>`. Crawlers fetch this once, then enqueue every shard.
 *
 * Keep the shard count in sync with the SHARDS array in `app/sitemap.ts`.
 */

const SHARD_COUNT = 4 // core, programmatic, vendors, images — see app/sitemap.ts

export const dynamic = "force-dynamic"

export async function GET() {
  const lastmod = new Date().toISOString()

  const body =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    Array.from({ length: SHARD_COUNT })
      .map(
        (_, idx) =>
          `  <sitemap>\n` +
          `    <loc>${SITE_URL}/sitemap/${idx}.xml</loc>\n` +
          `    <lastmod>${lastmod}</lastmod>\n` +
          `  </sitemap>`,
      )
      .join("\n") +
    `\n</sitemapindex>\n`

  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      // Search engines re-fetch the index occasionally; let them cache for
      // an hour at the edge so we don't re-render on every crawler hit.
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  })
}
