/**
 * Venue os — /dashboard/venue-os
 *
 * Generated by scripts/cypress-generate-module-specs.mjs, then extended by
 * hand. The generator will not overwrite this file again.
 *
 * `moduleSuite` is the shared contract every module must satisfy —
 * reachability, no console errors, no failing API calls, no horizontal
 * overflow at 1366 or 360, accessible names, heading order, focus ring. Add
 * cases specific to Venue os in the block underneath it: the contract is
 * the floor, not the test plan.
 */
import { moduleSuite } from "../../support/module-suite";

moduleSuite({
  route: "/dashboard/venue-os",
  name: "Venue os",
  expects: {
      "pageHeader": false,
      "dataTable": false,
      "statCard": true,
      "tabs": true,
      "emptyState": true
  },
});

// ─── Venue os-specific cases ─────────────────────────────────────────────
// Nothing here yet. A module with only the shared contract is COVERED, not
// TESTED — the contract proves the screen is not broken, not that the feature
// works. See leads.cy.ts for the depth each module is heading towards.
