import type { VendorType, Vendor } from "./types"

export const cities = ["All Cities", "Lahore", "Islamabad", "Karachi", "Faisalabad", "Peshawar"]

export const vendorTypes: Record<VendorType, string[]> = {
  venues: ["All Types", "Banquet Hall", "Marquee", "Outdoor", "Hall"],
  photographers: ["All Types", "Traditional", "Candid", "Cinematic", "Drone"],
  makeupArtists: ["All Types", "Bridal", "Party", "HD", "Airbrush"],
  decor: ["All Types", "Traditional", "Modern", "Rustic", "Minimalist"],
  catering: ["All Types", "Buffet", "Plated", "Food Stations", "Cocktail Style"],
  hennaArtists: ["All Types", "Traditional", "Arabic", "Indo-Arabic", "Modern"],
  weddingStationery: ["All Types", "Traditional", "Modern", "Handmade", "Digital"],
  bridalWear: ["All Types", "Traditional", "Contemporary", "Fusion", "Designer"],
  carRental: ["All Types", "Luxury", "Vintage", "Sports", "Limousine"],
}

export const cancellationPolicies = ["All Policies", "Refundable", "Non-refundable", "Partially Refundable"]

export const amenities: Record<VendorType, string[]> = {
  venues: ["Parking Space", "Wheelchair Accessible", "Air Conditioning", "Catering Services", "DJ Services"],
  photographers: ["High-resolution Images", "Album Design", "Drone Photography", "Same-day Editing", "Photo Booth"],
  makeupArtists: ["Hair Styling", "Airbrush Makeup", "False Lashes", "Bridal Trial", "Group Discounts"],
  decor: ["Floral Arrangements", "Lighting", "Furniture Rental", "Backdrop Design", "Table Settings"],
  catering: ["Customized Menu", "Vegetarian Options", "Halal Options", "Live Stations", "Dessert Bar"],
  hennaArtists: ["Natural Henna", "Black Henna", "Glitter Designs", "Bridal Package", "Group Discounts"],
  weddingStationery: ["Custom Design", "Calligraphy", "Eco-friendly Options", "Rush Orders", "Addressing Service"],
  bridalWear: ["Custom Sizing", "Alterations", "Accessories", "Bridal Consultation", "Bridesmaid Dresses"],
  carRental: ["Chauffeur Service", "Decorated Cars", "Multiple Car Options", "Flexible Hours", "Insurance Included"],
}

export const staffOptions = ["male", "female", "transgender", "all"]

export const vendors: Record<VendorType, Vendor[]> = {
  venues: [
    {
      id: 1,
      name: "Royal Palace Banquet",
      images: ["/venues/royal-palace-1.jpg", "/venues/royal-palace-2.jpg"],
      location: "Lahore",
      rating: 4.8,
      reviews: [],
      price: 150000,
      type: "Banquet Hall",
      capacity: 500,
      amenities: ["Parking Space", "Air Conditioning", "Catering Services"],
      cancellationPolicy: "Partially Refundable",
      sponsored: true,
      packages: [
        { id: 1, name: "Basic", price: 150000, description: "Basic package for up to 300 guests", items: ["Venue rental", "Basic decor", "Sound system"] },
        { id: 2, name: "Premium", price: 250000, description: "Premium package for up to 500 guests", items: ["Venue rental", "Premium decor", "Sound system", "Catering"] },
      ],
      description: "Royal Palace Banquet is a luxurious venue perfect for grand weddings and events.",
      staff: ["Manager", "Event Coordinator", "Catering Staff"],
    },
    {
      id: 2,
      name: "Green Meadows",
      images: ["/venues/green-meadows-1.jpg", "/venues/green-meadows-2.jpg"],
      location: "Islamabad",
      rating: 4.6,
      reviews: [],
      price: 100000,
      type: "Outdoor",
      capacity: 300,
      amenities: ["Parking Space", "Catering Services", "DJ Services"],
      cancellationPolicy: "Refundable",
      sponsored: false,
      packages: [
        { id: 1, name: "Basic", price: 100000, description: "Basic package for up to 200 guests", items: ["Venue rental", "Basic decor"] },
        { id: 2, name: "Deluxe", price: 150000, description: "Deluxe package for up to 300 guests", items: ["Venue rental", "Deluxe decor", "Catering", "DJ"] },
      ],
      description: "Green Meadows offers a beautiful outdoor setting for your dream wedding.",
      staff: ["Manager", "Gardener", "Event Staff"],
    },
    {
      id: 3,
      name: "Crystal Ballroom",
      images: ["/venues/crystal-ballroom-1.jpg", "/venues/crystal-ballroom-2.jpg"],
      location: "Karachi",
      rating: 4.9,
      reviews: [],
      price: 200000,
      type: "Hall",
      capacity: 400,
      amenities: ["Parking Space", "Wheelchair Accessible", "Air Conditioning", "Catering Services"],
      cancellationPolicy: "Non-refundable",
      sponsored: true,
      packages: [
        { id: 1, name: "Silver", price: 200000, description: "Silver package for up to 300 guests", items: ["Venue rental", "Decor", "Catering"] },
        { id: 2, name: "Gold", price: 300000, description: "Gold package for up to 400 guests", items: ["Venue rental", "Premium decor", "Catering", "DJ", "Photography"] },
      ],
      description: "Crystal Ballroom is an elegant venue with state-of-the-art facilities for your special day.",
      staff: ["Manager", "Event Planner", "Catering Team"],
    },
    {
      id: 4,
      name: "Sunset Marquee",
      images: ["/venues/sunset-marquee-1.jpg", "/venues/sunset-marquee-2.jpg"],
      location: "Faisalabad",
      rating: 4.5,
      reviews: [],
      price: 80000,
      type: "Marquee",
      capacity: 250,
      amenities: ["Parking Space", "Air Conditioning", "DJ Services"],
      cancellationPolicy: "Partially Refundable",
      sponsored: false,
      packages: [
        { id: 1, name: "Basic", price: 80000, description: "Basic package for up to 150 guests", items: ["Venue rental", "Basic decor"] },
        { id: 2, name: "Premium", price: 120000, description: "Premium package for up to 250 guests", items: ["Venue rental", "Premium decor", "DJ"] },
      ],
      description: "Sunset Marquee offers a romantic setting for intimate weddings and events.",
      staff: ["Manager", "Decor Team"],
    },
    {
      id: 5,
      name: "Grand Plaza",
      images: ["/venues/grand-plaza-1.jpg", "/venues/grand-plaza-2.jpg"],
      location: "Lahore",
      rating: 4.7,
      reviews: [],
      price: 180000,
      type: "Banquet Hall",
      capacity: 600,
      amenities: ["Parking Space", "Wheelchair Accessible", "Air Conditioning", "Catering Services", "DJ Services"],
      cancellationPolicy: "Refundable",
      sponsored: true,
      packages: [
        { id: 1, name: "Classic", price: 180000, description: "Classic package for up to 400 guests", items: ["Venue rental", "Decor", "Catering"] },
        { id: 2, name: "Luxury", price: 280000, description: "Luxury package for up to 600 guests", items: ["Venue rental", "Premium decor", "Catering", "DJ", "Photography", "Videography"] },
      ],
      description: "Grand Plaza is a versatile venue suitable for both intimate gatherings and large-scale celebrations.",
      staff: ["Manager", "Event Coordinator", "Catering Staff", "Technical Team"],
    },
    {
      id: 6,
      name: "Riverside Retreat",
      images: ["/venues/riverside-retreat-1.jpg", "/venues/riverside-retreat-2.jpg"],
      location: "Islamabad",
      rating: 4.8,
      reviews: [],
      price: 130000,
      type: "Outdoor",
      capacity: 350,
      amenities: ["Parking Space", "Catering Services", "DJ Services"],
      cancellationPolicy: "Partially Refundable",
      sponsored: false,
      packages: [
        { id: 1, name: "Rustic", price: 130000, description: "Rustic package for up to 200 guests", items: ["Venue rental", "Rustic decor", "Bonfire"] },
        { id: 2, name: "Elegant", price: 180000, description: "Elegant package for up to 350 guests", items: ["Venue rental", "Elegant decor", "Catering", "DJ", "Fireworks"] },
      ],
      description: "Riverside Retreat offers a picturesque setting by the water for a magical wedding experience.",
      staff: ["Manager", "Event Planner", "Catering Team", "Security"],
    },
    {
      id: 7,
      name: "Starlight Convention Center",
      images: ["/venues/starlight-convention-1.jpg", "/venues/starlight-convention-2.jpg"],
      location: "Karachi",
      rating: 4.9,
      reviews: [],
      price: 250000,
      type: "Hall",
      capacity: 800,
      amenities: ["Parking Space", "Wheelchair Accessible", "Air Conditioning", "Catering Services", "DJ Services"],
      cancellationPolicy: "Non-refundable",
      sponsored: true,
      packages: [
        { id: 1, name: "Silver Star", price: 250000, description: "Silver Star package for up to 500 guests", items: ["Venue rental", "Decor", "Catering", "Basic lighting"] },
        { id: 2, name: "Gold Star", price: 400000, description: "Gold Star package for up to 800 guests", items: ["Venue rental", "Premium decor", "Gourmet catering", "Advanced lighting and sound", "Photography", "Videography"] },
      ],
      description: "Starlight Convention Center is a state-of-the-art venue perfect for grand weddings and corporate events.",
      staff: ["General Manager", "Event Director", "Catering Manager", "Technical Director"],
    },
    {
      id: 8,
      name: "Heritage Manor",
      images: ["/venues/heritage-manor-1.jpg", "/venues/heritage-manor-2.jpg"],
      location: "Peshawar",
      rating: 4.7,
      reviews: [],
      price: 120000,
      type: "Banquet Hall",
      capacity: 300,
      amenities: ["Parking Space", "Air Conditioning", "Catering Services"],
      cancellationPolicy: "Partially Refundable",
      sponsored: false,
      packages: [
        { id: 1, name: "Traditional", price: 120000, description: "Traditional package for up to 200 guests", items: ["Venue rental", "Traditional decor", "Local cuisine catering"] },
        { id: 2, name: "Modern Fusion", price: 180000, description: "Modern Fusion package for up to 300 guests", items: ["Venue rental", "Contemporary decor", "Fusion cuisine catering", "DJ"] },
      ],
      description: "Heritage Manor blends traditional charm with modern amenities for a unique wedding experience.",
      staff: ["Manager", "Event Coordinator", "Chef", "Waitstaff"],
    },
    {
      id: 9,
      name: "Oasis Gardens",
      images: ["/venues/oasis-gardens-1.jpg", "/venues/oasis-gardens-2.jpg"],
      location: "Lahore",
      rating: 4.6,
      reviews: [],
      price: 160000,
      type: "Outdoor",
      capacity: 400,
      amenities: ["Parking Space", "Catering Services", "DJ Services"],
      cancellationPolicy: "Refundable",
      sponsored: true,
      packages: [
        { id: 1, name: "Garden Party", price: 160000, description: "Garden Party package for up to 250 guests", items: ["Venue rental", "Floral decor", "Buffet catering"] },
        { id: 2, name: "Luxury Oasis", price: 240000, description: "Luxury Oasis package for up to 400 guests", items: ["Venue rental", "Luxury decor", "Gourmet catering", "Live music", "Photography"] },
      ],
      description: "Oasis Gardens offers a lush, green setting for a fairytale wedding in the heart of the city.",
      staff: ["Garden Manager", "Event Planner", "Florist", "Catering Team"],
    },
    {
      id: 10,
      name: "Skyline Terrace",
      images: ["/venues/skyline-terrace-1.jpg", "/venues/skyline-terrace-2.jpg"],
      location: "Karachi",
      rating: 4.8,
      reviews: [],
      price: 200000,
      type: "Rooftop",
      capacity: 200,
      amenities: ["Parking Space", "Air Conditioning", "Catering Services", "DJ Services"],
      cancellationPolicy: "Non-refundable",
      sponsored: false,
      packages: [
        { id: 1, name: "Sunset Soiree", price: 200000, description: "Sunset Soiree package for up to 150 guests", items: ["Venue rental", "Minimalist decor", "Cocktail-style catering"] },
        { id: 2, name: "Starlight Gala", price: 300000, description: "Starlight Gala package for up to 200 guests", items: ["Venue rental", "Elegant decor", "Fine dining catering", "Live band", "Fireworks"] },
      ],
      description: "Skyline Terrace offers breathtaking views of the city skyline for an unforgettable rooftop wedding.",
      staff: ["Venue Manager", "Event Coordinator", "Mixologist", "Security Team"],
    },
  ],
  photographers: [
    {
      id: 1,
      name: "Capture Moments",
      images: ["/photographers/capture-moments-1.jpg", "/photographers/capture-moments-2.jpg"],
      location: "Lahore",
      rating: 4.9,
      reviews: [],
      price: 50000,
      type: "Traditional",
      amenities: ["High-resolution Images", "Album Design", "Same-day Editing"],
      sponsored: true,
      packages: [
        { id: 1, name: "Basic", price: 50000, description: "Basic package for up to 6 hours", items: ["Wedding ceremony coverage", "100 edited photos"] },
        { id: 2, name: "Premium", price: 80000, description: "Premium package for full day coverage", items: ["Full day coverage", "300 edited photos", "Wedding album", "Engagement shoot"] },
      ],
      description: "Capture Moments specializes in traditional wedding photography with a modern twist.",
      staff: ["Lead Photographer", "Assistant Photographer"],
    },
    {
      id: 2,
      name: "Candid Chronicles",
      images: ["/photographers/candid-chronicles-1.jpg", "/photographers/candid-chronicles-2.jpg"],
      location: "Karachi",
      rating: 4.8,
      reviews: [],
      price: 60000,
      type: "Candid",
      amenities: ["High-resolution Images", "Same-day Editing", "Photo Booth"],
      sponsored: false,
      packages: [
        { id: 1, name: "Story Teller", price: 60000, description: "8 hours of candid coverage", items: ["Ceremony and reception coverage", "150 edited photos", "Highlight reel"] },
        { id: 2, name: "Memory Maker", price: 90000, description: "Full day candid coverage", items: ["Full day coverage", "300 edited photos", "Cinematic highlight video", "Photo booth for 2 hours"] },
      ],
      description: "Candid Chronicles captures genuine moments and emotions throughout your special day.",
      staff: ["Lead Photographer", "Second Shooter", "Photo Booth Attendant"],
    },
    {
      id: 3,
      name: "Cinematic Visions",
      images: ["/photographers/cinematic-visions-1.jpg", "/photographers/cinematic-visions-2.jpg"],
      location: "Islamabad",
      rating: 4.9,
      reviews: [],
      price: 100000,
      type: "Cinematic",
      amenities: ["High-resolution Images", "Drone Photography", "Same-day Editing"],
      sponsored: true,
      packages: [
        { id: 1, name: "Silver Screen", price: 100000, description: "Cinematic coverage for up to 8 hours", items: ["Ceremony and reception film", "5-minute highlight reel", "Drone footage"] },
        { id: 2, name: "Blockbuster", price: 150000, description: "Full day cinematic experience", items: ["Full day film coverage", "10-minute feature film", "Drone footage", "Same-day edit screening at reception"] },
      ],
      description: "Cinematic Visions creates stunning, movie-like wedding films that tell your unique love story.",
      staff: ["Director", "Cinematographer", "Drone Operator", "Editor"],
    },
    {
      id: 4,
      name: "Drone Dreamers",
      images: ["/photographers/drone-dreamers-1.jpg", "/photographers/drone-dreamers-2.jpg"],
      location: "Lahore",
      rating: 4.7,
      reviews: [],
      price: 70000,
      type: "Drone",
      amenities: ["High-resolution Images", "Drone Photography", "Same-day Editing"],
      sponsored: false,
      packages: [
        { id: 1, name: "Sky High", price: 70000, description: "Drone coverage for key moments", items: ["Ceremony and venue aerial shots", "5-minute aerial highlight video"] },
        { id: 2, name: "Bird's Eye View", price: 120000, description: "Comprehensive drone and ground coverage", items: ["Full day drone and ground coverage", "10-minute cinematic video", "100 edited aerial photos"] },
      ],
      description: "Drone Dreamers specializes in capturing breathtaking aerial footage of your wedding day.",
      staff: ["Lead Drone Operator", "Ground Photographer", "Video Editor"],
    },
    {
      id: 5,
      name: "Timeless Treasures",
      images: ["/photographers/timeless-treasures-1.jpg", "/photographers/timeless-treasures-2.jpg"],
      location: "Faisalabad",
      rating: 4.6,
      reviews: [],
      price: 40000,
      type: "Traditional",
      amenities: ["High-resolution Images", "Album Design", "Bridal Portraits"],
      sponsored: false,
      packages: [
        { id: 1, name: "Classic", price: 40000, description: "Traditional coverage for ceremony", items: ["Ceremony coverage", "100 edited photos", "Printed album"] },
        { id: 2, name: "Heirloom", price: 70000, description: "Comprehensive traditional package", items: ["Full day coverage", "250 edited photos", "Deluxe printed album", "Bridal portrait session"] },
      ],
      description: "Timeless Treasures focuses on creating classic, elegant wedding photographs that stand the test of time.",
      staff: ["Photographer", "Assistant", "Album Designer"],
    },
    {
      id: 6,
      name: "Fusion Frames",
      images: ["/photographers/fusion-frames-1.jpg", "/photographers/fusion-frames-2.jpg"],
      location: "Karachi",
      rating: 4.8,
      reviews: [],
      price: 80000,
      type: "Candid",
      amenities: ["High-resolution Images", "Same-day Editing", "Engagement Shoot"],
      sponsored: true,
      packages: [
        { id: 1, name: "Blend", price: 80000, description: "Mix of traditional and candid coverage", items: ["8 hours of coverage", "200 edited photos", "Engagement shoot"] },
        { id: 2, name: "Fusion Deluxe", price: 120000, description: "Comprehensive fusion package", items: ["Full day coverage", "400 edited photos", "Engagement shoot", "Same-day slideshow", "Signature wedding album"] },
      ],
      description: "Fusion Frames combines traditional poses with candid moments for a well-rounded wedding album.",
      staff: ["Lead Photographer", "Second Shooter", "Editor"],
    },
    {
      id: 7,
      name: "Vintage Vibes",
      images: ["/photographers/vintage-vibes-1.jpg", "/photographers/vintage-vibes-2.jpg"],
      location: "Peshawar",
      rating: 4.7,
      reviews: [],
      price: 55000,
      type: "Traditional",
      amenities: ["High-resolution Images", "Film Photography", "Custom Photo Box"],
      sponsored: false,
      packages: [
        { id: 1, name: "Retro", price: 55000, description: "Vintage-style digital coverage", items: ["6 hours of coverage", "150 edited photos with vintage filters", "20 film photos"] },
        { id: 2, name: "Nostalgia", price: 85000, description: "Full vintage experience", items: ["Full day coverage", "300 edited digital photos", "50 film photos", "Custom wooden photo box"] },
      ],
      description: "Vintage Vibes specializes in creating wedding photos with a beautiful, timeless aesthetic.",
      staff: ["Vintage Specialist Photographer", "Film Developer"],
    },
    {
      id: 8,
      name: "Action Shots",
      images: ["/photographers/action-shots-1.jpg", "/photographers/action-shots-2.jpg"],
      location: "Islamabad",
      rating: 4.9,
      reviews: [],
      price: 90000,
      type: "Candid",
      amenities: ["High-resolution Images", "Same-day Editing", "Live Streaming"],
      sponsored: true,
      packages: [
        { id: 1, name: "Dynamic Duo", price: 90000, description: "Two photographers for non-stop action", items: ["8 hours of coverage", "300 action-packed photos", "Live streaming of ceremony"] },
        { id: 2, name: "Action Packed", price: 130000, description: "Comprehensive action coverage", items: ["Full day coverage with two photographers", "500 dynamic photos", "Live streaming of full event", "30-minute documentary-style video"] },
      ],
      description: "Action Shots captures every exciting moment of your wedding day, ensuring no special moment is missed.",
      staff: ["Two Lead Photographers", "Live Streaming Technician", "Editor"],
    },
    {
      id: 9,
      name: "Destination Dreams",
      images: ["/photographers/destination-dreams-1.jpg", "/photographers/destination-dreams-2.jpg"],
      location: "Lahore",
      rating: 4.8,
      reviews: [],
      price: 150000,
      type: "Cinematic",
      amenities: ["High-resolution Images", "Drone Photography", "Destination Coverage"],
      sponsored: false,
      packages: [
        { id: 1, name: "Wanderlust", price: 150000, description: "Destination wedding coverage", items: ["2 days of coverage", "500 edited photos", "10-minute cinematic film", "Drone footage"] },
        { id: 2, name: "Globe Trotter", price: 250000, description: "Extended destination coverage", items: ["3 days of coverage", "800 edited photos", "20-minute cinematic film", "Drone footage", "Pre-wedding shoot at destination"] },
      ],
      description: "Destination Dreams specializes in capturing beautiful weddings in exotic locations around Pakistan and beyond.",
      staff: ["Lead Photographer", "Cinematographer", "Drone Operator"],
    },
    {
      id: 10,
      name: "Digital Artistry",
      images: ["/photographers/digital-artistry-1.jpg", "/photographers/digital-artistry-2.jpg"],
      location: "Karachi",
      rating: 4.7,
      reviews: [],
      price: 75000,
      type: "Modern",
      amenities: ["High-resolution Images", "Advanced Post-processing", "Digital Album"],
      sponsored: true,
      packages: [
        { id: 1, name: "Pixel Perfect", price: 75000, description: "Modern digital coverage", items: ["8 hours of coverage", "200 artistically edited photos", "Digital album"] },
        { id: 2, name: "Digital Masterpiece", price: 110000, description: "Comprehensive digital art package", items: ["Full day coverage", "400 artistically edited photos", "Digital album", "5 large format fine art prints"] },
      ],
      description: "Digital Artistry pushes the boundaries of wedding photography with creative editing and modern techniques.",
      staff: ["Photographer", "Digital Artist", "Graphic Designer"],
    },
  ],
  makeupArtists: [
    {
      id: 1,
      name: "Glamour Glow",
      images: ["/makeup-artists/glamour-glow-1.jpg", "/makeup-artists/glamour-glow-2.jpg"],
      location: "Lahore",
      rating: 4.9,
      reviews: [],
      price: 25000,
      type: "Bridal",
      amenities: ["Hair Styling", "Airbrush Makeup", "False Lashes"],
      sponsored: true,
      packages: [
        { id: 1, name: "Bridal Bliss", price: 25000, description: "Bridal makeup and hair", items: ["Bridal makeup", "Hairstyling", "False lashes", "Touch-up kit"] },
        { id: 2, name: "Wedding Party Glam", price: 50000, description: "Bridal and bridesmaids package", items: ["Bridal makeup and hair", "Makeup for 3 bridesmaids", "Hairstyling for bride and bridesmaids"] },
      ],
      description: "Glamour Glow specializes in creating stunning bridal looks that last all day and night.",
      staff: ["Lead Makeup Artist", "Hairstylist"],
    },
    {
      id: 2,
      name: "Natural Beauty",
      images: ["/makeup-artists/natural-beauty-1.jpg", "/makeup-artists/natural-beauty-2.jpg"],
      location: "Islamabad",
      rating: 4.7,
      reviews: [],
      price: 20000,
      type: "HD",
      amenities: ["Organic Products", "Skin Prep", "Touch-up Kit"],
      sponsored: false,
      packages: [
        { id: 1, name: "Fresh Face", price: 20000, description: "Natural bridal makeup", items: ["HD makeup application", "Natural hairstyling", "Organic skincare prep"] },
        { id: 2, name: "Radiant Bride", price: 35000, description: "Comprehensive natural bridal package", items: ["HD makeup application", "Natural hairstyling", "Pre-wedding skin consultation", "Day-of touch-up service"] },
      ],
      description: "Natural Beauty focuses on enhancing your features with a light, fresh makeup look.",
      staff: ["Makeup Artist", "Skincare Specialist"],
    },
    {
      id: 3,
      name: "Glitz and Glam",
      images: ["/makeup-artists/glitz-and-glam-1.jpg", "/makeup-artists/glitz-and-glam-2.jpg"],
      location: "Karachi",
      rating: 4.8,
      reviews: [],
      price: 30000,
      type: "Party",
      amenities: ["Airbrush Makeup", "Hair Extensions", "Glitter Options"],
      sponsored: true,
      packages: [
        { id: 1, name: "Party Ready", price: 30000, description: "Glamorous party makeup", items: ["Full glam makeup", "Hairstyling with extensions", "Glitter accents"] },
        { id: 2, name: "Red Carpet Glam", price: 50000, description: "Head-to-toe glamour package", items: ["Airbrushed makeup", "Luxury hairstyling", "Lash extensions", "Nail styling"] },
      ],
      description: "Glitz and Glam creates show-stopping looks perfect for brides who want to make a statement.",
      staff: ["Makeup Artist", "Hair Stylist", "Nail Technician"],
    },
    {
      id: 4,
      name: "Bridal Blush",
      images: ["/makeup-artists/bridal-blush-1.jpg", "/makeup-artists/bridal-blush-2.jpg"],
      location: "Faisalabad",
      rating: 4.6,
      reviews: [],
      price: 18000,
      type: "Bridal",
      amenities: ["Traditional Techniques", "Henna Application", "Jewelry Styling"],
      sponsored: false,
      packages: [
        { id: 1, name: "Traditional Bride", price: 18000, description: "Classic bridal makeup", items: ["Traditional makeup application", "Bridal hairstyling", "Henna touch-ups"] },
        { id: 2, name: "Complete Bridal Package", price: 30000, description: "Full traditional bridal service", items: ["Bridal makeup and hair", "Henna application", "Jewelry and dupatta styling", "Family member touch-ups"] },
      ],
      description: "Bridal Blush specializes in traditional Pakistani bridal makeup and styling.",
      staff: ["Bridal Makeup Artist", "Henna Artist"],
    },
    {
      id: 5,
      name: "Airbrush Allure",
      images: ["/makeup-artists/airbrush-allure-1.jpg", "/makeup-artists/airbrush-allure-2.jpg"],
      location: "Lahore",
      rating: 4.9,
      reviews: [],
      price: 35000,
      type: "Airbrush",
      amenities: ["Airbrush Makeup", "Waterproof Options", "HD Photography Finish"],
      sponsored: true,
      packages: [
        { id: 1, name: "Flawless Finish", price: 35000, description: "Airbrush bridal makeup", items: ["Airbrush makeup application", "Waterproof setting", "HD-ready finish"] },
        { id: 2, name: "Picture Perfect", price: 55000, description: "Complete airbrush and styling package", items: ["Airbrush makeup", "Hairstyling", "Lash extensions", "Touch-up kit for photos"] },
      ],
      description: "Airbrush Allure provides long-lasting, photo-ready makeup using the latest airbrush technology.",
      staff: ["Airbrush Specialist", "Hairstylist"],
    },
    {
      id: 6,
      name: "Mehendi Magic",
      images: ["/makeup-artists/mehendi-magic-1.jpg", "/makeup-artists/mehendi-magic-2.jpg"],
      location: "Karachi",
      rating: 4.7,
      reviews: [],
      price: 15000,
      type: "Bridal",
      amenities: ["Henna Application", "Natural Henna Options", "Henna Touch-ups"],
      sponsored: false,
      packages: [
        { id: 1, name: "Bridal Henna", price: 15000, description: "Intricate bridal henna", items: ["Full hands and feet bridal henna", "Natural henna option", "Touch-up kit"] },
        { id: 2, name: "Mehendi Celebration", price: 30000, description: "Henna for bride and guests", items: ["Bridal henna", "Henna for 10 guests", "Henna care kit"] },
      ],
      description: "Mehendi Magic specializes in intricate henna designs for brides and wedding parties.",
      staff: ["Lead Henna Artist", "Assistant Henna Artist"],
    },
    {
      id: 7,
      name: "Glow Getters",
      images: ["/makeup-artists/glow-getters-1.jpg", "/makeup-artists/glow-getters-2.jpg"],
      location: "Islamabad",
      rating: 4.8,
      reviews: [],
      price: 28000,
      type: "HD",
      amenities: ["HD Makeup", "Skin Prep", "Illuminating Techniques"],
      sponsored: true,
      packages: [
        { id: 1, name: "Radiant Bride", price: 28000, description: "HD bridal makeup for a natural glow", items: ["HD makeup application", "Skincare prep", "Illuminating techniques"] },
        { id: 2, name: "Glow Up Party", price: 45000, description: "HD makeup for bride and bridal party", items: ["Bridal HD makeup", "HD makeup for 3 bridesmaids", "Group touch-up service"] },
      ],
      description: "Glow Getters uses HD makeup techniques to create a radiant, camera-ready look for brides.",
      staff: ["HD Makeup Specialist", "Skincare Expert"],
    },
    {
      id: 8,
      name: "Vintage Vogue",
      images: ["/makeup-artists/vintage-vogue-1.jpg", "/makeup-artists/vintage-vogue-2.jpg"],
      location: "Lahore",
      rating: 4.6,
      reviews: [],
      price: 22000,
      type: "Party",
      amenities: ["Retro Styling", "Victory Rolls", "Red Lip Service"],
      sponsored: false,
      packages: [
        { id: 1, name: "Retro Glam", price: 22000, description: "Vintage-inspired bridal look", items: ["Vintage makeup application", "Retro hairstyling", "Red lip service"] },
        { id: 2, name: "Throwback Elegance", price: 40000, description: "Complete vintage styling for bride and party", items: ["Bridal vintage makeup and hair", "Styling for 2 bridesmaids", "Vintage accessories rental"] },
      ],
      description: "Vintage Vogue specializes in creating timeless, retro-inspired looks for brides and their parties.",
      staff: ["Vintage Makeup Artist", "Retro Hair Stylist"],
    },
    {
      id: 9,
      name: "Cultural Charm",
      images: ["/makeup-artists/cultural-charm-1.jpg", "/makeup-artists/cultural-charm-2.jpg"],
      location: "Peshawar",
      rating: 4.7,
      reviews: [],
      price: 20000,
      type: "Bridal",
      amenities: ["Traditional Techniques", "Regional Styles", "Cultural Accessories"],
      sponsored: true,
      packages: [
        { id: 1, name: "Regional Bride", price: 20000, description: "Traditional bridal makeup and styling", items: ["Regional bridal makeup", "Traditional hairstyling", "Cultural accessories styling"] },
        { id: 2, name: "Heritage Celebration", price: 35000, description: "Full cultural bridal package", items: ["Bridal makeup and hair", "Dupatta and jewelry styling", "Henna application", "Family styling consultation"] },
      ],
      description: "Cultural Charm focuses on traditional Pakistani bridal looks, specializing in regional styles and techniques.",
      staff: ["Cultural Makeup Artist", "Traditional Hairstylist"],
    },
    {
      id: 10,
      name: "Eco Elegance",
      images: ["/makeup-artists/eco-elegance-1.jpg", "/makeup-artists/eco-elegance-2.jpg"],
      location: "Islamabad",
      rating: 4.8,
      reviews: [],
      price: 26000,
      type: "HD",
      amenities: ["Organic Products", "Cruelty-free Options", "Eco-friendly Tools"],
      sponsored: false,
      packages: [
        { id: 1, name: "Green Goddess", price: 26000, description: "Eco-friendly bridal makeup", items: ["Organic makeup application", "Natural hairstyling", "Eco-friendly lashes"] },
        { id: 2, name: "Sustainable Style", price: 45000, description: "Complete eco-conscious bridal package", items: ["Bride and bridal party organic makeup", "Eco-friendly hair styling", "Sustainable touch-up kit"] },
      ],
      description: "Eco Elegance provides beautiful, long-lasting bridal looks using only eco-friendly and cruelty-free products.",
      staff: ["Eco Makeup Specialist", "Organic Hairstylist"],
    },
  ],
  decor: [
    {
      id: 1,
      name: "Elegant Affairs",
      images: ["/decor/elegant-affairs-1.jpg", "/decor/elegant-affairs-2.jpg"],
      location: "Lahore",
      rating: 4.9,
      reviews: [],
      price: 150000,
      type: "Modern",
      amenities: ["Floral Arrangements", "Lighting", "Furniture Rental"],
      sponsored: true,
      packages: [
        { id: 1, name: "Chic Simplicity", price: 150000, description: "Modern minimalist decor", items: ["Sleek centerpieces", "LED lighting", "Modern furniture setup"] },
        { id: 2, name: "Luxe Modern", price: 250000, description: "High-end modern decor", items: ["Designer floral arrangements", "Custom lighting installation", "Luxury modern furniture", "Photo booth setup"] },
      ],
      description: "Elegant Affairs creates sophisticated, modern wedding decor that transforms any venue into a contemporary wonderland.",
      staff: ["Lead Designer", "Floral Artist", "Lighting Technician"],
    },
    {
      id: 2,
      name: "Timeless Traditions",
      images: ["/decor/timeless-traditions-1.jpg", "/decor/timeless-traditions-2.jpg"],
      location: "Karachi",
      rating: 4.8,
      reviews: [],
      price: 120000,
      type: "Traditional",
      amenities: ["Traditional Decor", "Mandap Setup", "Cultural Elements"],
      sponsored: false,
      packages: [
        { id: 1, name: "Classic Charm", price: 120000, description: "Traditional Pakistani wedding decor", items: ["Ornate mandap", "Traditional floral arrangements", "Cultural props and elements"] },
        { id: 2, name: "Royal Heritage", price: 200000, description: "Luxury traditional decor", items: ["Grand mandap with fresh flowers", "Traditional seating area", "Antique props", "Traditional music arrangement"] },
      ],
      description: "Timeless Traditions specializes in creating authentic, culturally rich wedding decor that honors Pakistani heritage.",
      staff: ["Cultural Decor Specialist", "Floral Team", "Prop Master"],
    },
    {
      id: 3,
      name: "Rustic Romance",
      images: ["/decor/rustic-romance-1.jpg", "/decor/rustic-romance-2.jpg"],
      location: "Islamabad",
      rating: 4.7,
      reviews: [],
      price: 100000,
      type: "Rustic",
      amenities: ["Wooden Elements", "Vintage Props", "Outdoor Setups"],
      sponsored: true,
      packages: [
        { id: 1, name: "Country Charm", price: 100000, description: "Cozy rustic decor", items: ["Wooden arch", "Mason jar centerpieces", "Hay bale seating"] },
        { id: 2, name: "Enchanted Forest", price: 180000, description: "Elaborate rustic outdoor decor", items: ["Tree-inspired mandap", "Wildflower arrangements", "Fairy light canopy", "Rustic lounge area"] },
      ],
      description: "Rustic Romance brings the charm of the countryside to your wedding with warm, inviting decor setups.",
      staff: ["Rustic Design Specialist", "Carpenter", "Outdoor Event Coordinator"],
    },
    {
      id: 4,
      name: "Opulent Occasions",
      images: ["/decor/opulent-occasions-1.jpg", "/decor/opulent-occasions-2.jpg"],
      location: "Lahore",
      rating: 4.9,
      reviews: [],
      price: 300000,
      type: "Luxury",
      amenities: ["Crystal Decor", "Gold Accents", "Premium Floral"],
      sponsored: true,
      packages: [
        { id: 1, name: "Golden Glamour", price: 300000, description: "Luxurious gold-themed decor", items: ["Crystal chandeliers", "Gold chiavari chairs", "Premium floral centerpieces"] },
        { id: 2, name: "Royal Extravaganza", price: 500000, description: "Ultimate luxury wedding decor", items: ["Custom-designed mandap", "Swarovski crystal details", "Exotic flower imports", "LED dance floor"] },
      ],
      description: "Opulent Occasions creates breathtakingly luxurious wedding setups for couples who want nothing but the best.",
      staff: ["Luxury Event Designer", "Crystal Decor Specialist", "Premium Floral Team"],
    },
    {
      id: 5,
      name: "Bohemian Bliss",
      images: ["/decor/bohemian-bliss-1.jpg", "/decor/bohemian-bliss-2.jpg"],
      location: "Karachi",
      rating: 4.6,
      reviews: [],
      price: 80000,
      type: "Boho",
      amenities: ["Macrame Decor", "Pampas Grass", "Eclectic Furniture"],
      sponsored: false,
      packages: [
        { id: 1, name: "Free Spirit", price: 80000, description: "Relaxed boho decor", items: ["Macrame backdrop", "Pampas grass arrangements", "Mismatched vintage furniture"] },
        { id: 2, name: "Boho Luxe", price: 150000, description: "Upscale bohemian decor", items: ["Large macrame installations", "Mix of dried and fresh flowers", "Luxury lounge areas", "Moroccan lanterns"] },
      ],
      description: "Bohemian Bliss creates free-spirited, eclectic wedding decor for couples who want a relaxed yet stylish atmosphere.",
      staff: ["Boho Style Expert", "Macrame Artist", "Vintage Furniture Curator"],
    },
    {
      id: 6,
      name: "Tech Transformations",
      images: ["/decor/tech-transformations-1.jpg", "/decor/tech-transformations-2.jpg"],
      location: "Islamabad",
      rating: 4.8,
      reviews: [],
      price: 200000,
      type: "Modern",
      amenities: ["LED Screens", "Projection Mapping", "Interactive Elements"],
      sponsored: true,
      packages: [
        { id: 1, name: "Digital Dreams", price: 200000, description: "High-tech wedding decor", items: ["LED flower wall", "Projection mapped cake", "Interactive guest book station"] },
        { id: 2, name: "Future Fantasy", price: 350000, description: "Cutting-edge tech-focused decor", items: ["360-degree projection mapping", "Holographic photo booth", "AI-controlled lighting", "Digital table centerpieces"] },
      ],
      description: "Tech Transformations uses cutting-edge technology to create futuristic, interactive wedding environments.",
      staff: ["Tech Decor Specialist", "AV Technician", "Interactive Designer"],
    },
    {
      id: 7,
      name: "Seasonal Splendor",
      images: ["/decor/seasonal-splendor-1.jpg", "/decor/seasonal-splendor-2.jpg"],
      location: "Lahore",
      rating: 4.7,
      reviews: [],
      price: 130000,
      type: "Seasonal",
      amenities: ["Seasonal Flowers", "Themed Props", "Weather Adaptations"],
      sponsored: false,
      packages: [
        { id: 1, name: "Spring Awakening", price: 130000, description: "Fresh spring-themed decor", items: ["Cherry blossom arrangements", "Pastel color scheme", "Butterfly motifs"] },
        { id: 2, name: "Winter Wonderland", price: 220000, description: "Magical winter wedding decor", items: ["Snow-covered trees", "Ice sculptures", "Cozy fire pits", "Fur throws"] },
      ],
      description: "Seasonal Splendor creates stunning wedding decor that celebrates the beauty of each season.",
      staff: ["Seasonal Decor Expert", "Prop Stylist", "Climate Control Specialist"],
    },
    {
      id: 8,
      name: "Minimalist Magic",
      images: ["/decor/minimalist-magic-1.jpg", "/decor/minimalist-magic-2.jpg"],
      location: "Karachi",
      rating: 4.8,
      reviews: [],
      price: 90000,
      type: "Minimalist",
      amenities: ["Clean Lines", "Monochrome Palette", "Geometric Shapes"],
      sponsored: true,
      packages: [
        { id: 1, name: "Less is More", price: 90000, description: "Elegant minimalist decor", items: ["Sleek white floral arrangements", "Geometric centerpieces", "Transparent chairs"] },
        { id: 2, name: "Minimalist Luxe", price: 160000, description: "High-end minimalist design", items: ["Custom acrylic structures", "Monochrome balloon installations", "LED light sculptures", "Minimalist lounge area"] },
      ],
      description: "Minimalist Magic creates clean, modern wedding decor that lets the beauty of simplicity shine.",
      staff: ["Minimalist Design Expert", "Modern Florist", "Lighting Designer"],
    },
    {
      id: 9,
      name: "Floral Fantasy",
      images: ["/decor/floral-fantasy-1.jpg", "/decor/floral-fantasy-2.jpg"],
      location: "Islamabad",
      rating: 4.9,
      reviews: [],
      price: 180000,
      type: "Floral",
      amenities: ["Exotic Flowers", "Living Walls", "Suspended Installations"],
      sponsored: true,
      packages: [
        { id: 1, name: "Blooming Bliss", price: 180000, description: "Lush floral-focused decor", items: ["Flower wall backdrop", "Hanging floral chandeliers", "Table runners with fresh flowers"] },
        { id: 2, name: "Botanical Paradise", price: 300000, description: "Extravagant floral wonderland", items: ["Floral mandap", "Suspended flower installations", "Living flower walls", "Exotic flower imports"] },
      ],
      description: "Floral Fantasy transforms venues into breathtaking gardens with innovative and lush floral designs.",
      staff: ["Master Florist", "Botanical Artist", "Floral Structure Engineer"],
    },
    {
      id: 10,
      name: "Destination Decor",
      images: ["/decor/destination-decor-1.jpg", "/decor/destination-decor-2.jpg"],
      location: "Lahore",
      rating: 4.7,
      reviews: [],
      price: 250000,
      type: "Themed",
      amenities: ["Location-Inspired Decor", "Cultural Elements", "Destination Props"],
      sponsored: false,
      packages: [
        { id: 1, name: "Tropical Paradise", price: 250000, description: "Beach-inspired wedding decor", items: ["Palm leaf arrangements", "Seashell accents", "Tiki torches", "Sand-filled decor"] },
        { id: 2, name: "Global Glamour", price: 400000, description: "Multi-cultural destination-inspired decor", items: ["Moroccan lanterns", "Italian villa facade", "Japanese zen garden", "Indian palace-inspired mandap"] },
      ],
      description: "Destination Decor brings the essence of world-famous locations to your wedding, creating an unforgettable themed experience.",
      staff: ["Theme Design Specialist", "Cultural Decor Expert", "Prop Master"],
    },
  ],
  catering: [
    {
      id: 1,
      name: "Flavors of Pakistan",
      images: ["/catering/flavors-of-pakistan-1.jpg", "/catering/flavors-of-pakistan-2.jpg"],
      location: "Lahore",
      rating: 4.9,
      reviews: [],
      price: 1500,
      type: "Traditional",
      amenities: ["Live Cooking Stations", "Customized Menus", "Dietary Accommodations"],
      sponsored: true,
      packages: [
        { id: 1, name: "Classic Feast", price: 1500, description: "Traditional Pakistani menu", items: ["Variety of kebabs", "Biryani", "Nihari", "Assorted naans", "Traditional desserts"] },
        { id: 2, name: "Royal Banquet", price: 2500, description: "Luxury Pakistani cuisine", items: ["Premium meat selections", "Seafood options", "Gourmet biryanis", "Live cooking stations", "Fusion desserts"] },
      ],
      description: "Flavors of Pakistan offers authentic Pakistani cuisine with a modern twist, perfect for weddings celebrating cultural heritage.",
      staff: ["Head Chef", "Sous Chefs", "Service Staff"],
    },
    {
      id: 2,
      name: "Global Gourmet",
      images: ["/catering/global-gourmet-1.jpg", "/catering/global-gourmet-2.jpg"],
      location: "Karachi",
      rating: 4.8,
      reviews: [],
      price: 2000,
      type: "International",
      amenities: ["Multi-cuisine Options", "Fusion Dishes", "International Chefs"],
      sponsored: false,
      packages: [
        { id: 1, name: "World Tour", price: 2000, description: "International cuisine selection", items: ["Italian pasta station", "Japanese sushi bar", "Mediterranean mezze", "American BBQ", "French pastries"] },
        { id: 2, name: "Fusion Fiesta", price: 3000, description: "Innovative fusion menu", items: ["Thai-spiced seekh kebabs", "Tandoori pizza", "Butter chicken tacos", "Gulab jamun cheesecake", "Live fusion stations"] },
      ],
      description: "Global Gourmet brings flavors from around the world to your wedding, offering a diverse and exciting culinary experience.",
      staff: ["International Head Chef", "Cuisine Specialists", "Multilingual Service Team"],
    },
    {
      id: 3,
      name: "Green Leaf Catering",
      images: ["/catering/green-leaf-catering-1.jpg", "/catering/green-leaf-catering-2.jpg"],
      location: "Islamabad",
      rating: 4.7,
      reviews: [],
      price: 1800,
      type: "Vegetarian",
      amenities: ["Organic Ingredients", "Vegan Options", "Eco-friendly Packaging"],
      sponsored: true,
      packages: [
        { id: 1, name: "Garden Fresh", price: 1800, description: "Vegetarian delights", items: ["Grilled vegetable platters", "Paneer tikka", "Vegetable biryanis", "Dairy-free options", "Fruit-based desserts"] },
        { id: 2, name: "Vegan Voyage", price: 2200, description: "Gourmet vegan experience", items: ["Jackfruit kebabs", "Cashew cheese canapes", "Vegan biryanis", "Plant-based curries", "Vegan dessert bar"] },
      ],
      description: "Green Leaf Catering specializes in delicious vegetarian and vegan options, perfect for health-conscious and environmentally-aware couples.",
      staff: ["Vegetarian Chef", "Nutritionist", "Eco-friendly Packaging Expert"],
    },
    {
      id: 4,
      name: "Royal Rasoi",
      images: ["/catering/royal-rasoi-1.jpg", "/catering/royal-rasoi-2.jpg"],
      location: "Lahore",
      rating: 4.9,
      reviews: [],
      price: 2500,
      type: "Luxury",
      amenities: ["Premium Ingredients", "Gold-leaf Garnishes", "Personalized Menu Cards"],
      sponsored: true,
      packages: [
        { id: 1, name: "Maharaja's Feast", price: 2500, description: "Opulent North Indian cuisine", items: ["Gold-leaf topped kebabs", "Saffron-infused biryani", "Truffle naan", "Lobster curry", "Designer desserts"] },
        { id: 2, name: "Imperial Indulgence", price: 3500, description: "Ultimate luxury dining experience", items: ["Caviar starters", "Wagyu beef kebabs", "Truffle risotto", "Molecular gastronomy station", "Edible art desserts"] },
      ],
      description: "Royal Rasoi offers an unparalleled luxury dining experience, fit for royalty, with the finest ingredients and impeccable presentation.",
      staff: ["Celebrity Chef", "Gourmet Specialists", "Butler-style Service Team"],
    },
    {
      id: 5,
      name: "Desi Dhaba",
      images: ["/catering/desi-dhaba-1.jpg", "/catering/desi-dhaba-2.jpg"],
      location: "Faisalabad",
      rating: 4.6,
      reviews: [],
      price: 1200,
      type: "Street Food",
      amenities: ["Live Cooking", "Rustic Presentation", "Late-night Snack Options"],
      sponsored: false,
      packages: [
        { id: 1, name: "Street Feast", price: 1200, description: "Popular street food items", items: ["Gol gappay station", "Bun kebabs", "Chaat corner", "Freshly fried samosas", "Falooda bar"] },
        { id: 2, name: "Dhaba Delight", price: 1800, description: "Enhanced street food experience", items: ["Tandoor station", "Karahi corner", "Lassi bar", "Jalebi station", "Paan counter"] },
      ],
      description: "Desi Dhaba brings the vibrant flavors of Pakistani street food to your wedding, offering a fun and nostalgic dining experience.",
      staff: ["Street Food Experts", "Chai Wala", "Traditional Cook"],
    },
    {
      id: 6,
      name: "Wellness Bites",
      images: ["/catering/wellness-bites-1.jpg", "/catering/wellness-bites-2.jpg"],
      location: "Islamabad",
      rating: 4.7,
      reviews: [],
      price: 1600,
      type: "Health-Focused",
      amenities: ["Nutritional Information Display", "Allergen-free Options", "Superfood Ingredients"],
      sponsored: true,
      packages: [
        { id: 1, name: "Nutrient Rich", price: 1600, description: "Balanced and healthy menu", items: ["Quinoa salad bar", "Grilled lean proteins", "Vegetable-packed curries", "Whole grain breads", "Sugar-free desserts"] },
        { id: 2, name: "Vitality Feast", price: 2000, description: "Gourmet health-focused dining", items: ["Açai bowl station", "Keto-friendly options", "Probiotic-rich dishes", "Cold-pressed juice bar", "Protein-packed desserts"] },
      ],
      description: "Wellness Bites caters to health-conscious couples, offering nutritious and delicious options without compromising on taste.",
      staff: ["Nutritionist Chef", "Dietary Specialist", "Health Coach"],
    },
    {
      id: 7,
      name: "Spice Route",
      images: ["/catering/spice-route-1.jpg", "/catering/spice-route-2.jpg"],
      location: "Karachi",
      rating: 4.8,
      reviews: [],
      price: 1800,
      type: "Multi-Regional",
      amenities: ["Regional Specialties", "Spice Tasting Station", "Recipe Cards for Guests"],
      sponsored: false,
      packages: [
        { id: 1, name: "Flavors of Pakistan", price: 1800, description: "Multi-regional Pakistani cuisine", items: ["Peshawari chapli kebabs", "Sindhi biryani", "Balochi sajji", "Kashmiri rogan josh", "Regional dessert platter"] },
        { id: 2, name: "Subcontinental Journey", price: 2200, description: "Expanded South Asian flavors", items: ["Bengali fish curry", "Goan vindaloo", "Nepali momos", "Sri Lankan hoppers", "Pan-Asian dessert fusion"] },
      ],
      description: "Spice Route takes your guests on a culinary journey through the diverse regions of Pakistan and beyond, showcasing unique flavors and techniques.",
      staff: ["Regional Cuisine Experts", "Spice Master", "Cultural Food Historian"],
    },
    {
      id: 8,
      name: "Buffet Bonanza",
      images: ["/catering/buffet-bonanza-1.jpg", "/catering/buffet-bonanza-2.jpg"],
      location: "Lahore",
      rating: 4.6,
      reviews: [],
      price: 1400,
      type: "Buffet",
      amenities: ["Extensive Spread", "Live Stations", "Flexible Dining Times"],
      sponsored: true,
      packages: [
        { id: 1, name: "Grand Buffet", price: 1400, description: "Extensive multi-cuisine buffet", items: ["International salad bar", "Soup station", "Variety of main courses", "Live pasta counter", "Dessert island"] },
        { id: 2, name: "Luxury Spread", price: 1800, description: "Premium buffet experience", items: ["Seafood bar", "Carving station", "Global cuisine corners", "Flambé desserts", "Chocolate fountain"] },
      ],
      description: "Buffet Bonanza offers an extensive range of dishes, ensuring there's something for everyone with the flexibility of a buffet setting.",
      staff: ["Buffet Manager", "Station Chefs", "Replenishment Team"],
    },
    {
      id: 9,
      name: "Midnight Munchies",
      images: ["/catering/midnight-munchies-1.jpg", "/catering/midnight-munchies-2.jpg"],
      location: "Islamabad",
      rating: 4.7,
      reviews: [],
      price: 1000,
      type: "Late-Night",
      amenities: ["Portable Food Options", "Hangover Cures", "Breakfast-inspired Items"],
      sponsored: false,
      packages: [
        { id: 1, name: "After-Party Bites", price: 1000, description: "Late-night snack selection", items: ["Mini sliders", "Loaded fries", "Pizza station", "Dessert shots", "Mocktail bar"] },
        { id: 2, name: "Sunrise Specialties", price: 1400, description: "Extended late-night to early morning options", items: ["Breakfast burritos", "Waffle station", "Detox juices", "Desi breakfast items", "Coffee and tea bar"] },
      ],
      description: "Midnight Munchies specializes in satisfying late-night cravings, keeping your guests energized and happy until the early hours.",
      staff: ["Night Shift Chef", "Barista", "Energy Drink Mixologist"],
    },
    {
      id: 10,
      name: "Culinary Canvas",
      images: ["/catering/culinary-canvas-1.jpg", "/catering/culinary-canvas-2.jpg"],
      location: "Karachi",
      rating: 4.9,
      reviews: [],
      price: 2800,
      type: "Artistic",
      amenities: ["Food Art Displays", "Edible Centerpieces", "Color-themed Menus"],
      sponsored: true,
      packages: [
        { id: 1, name: "Edible Art", price: 2800, description: "Visually stunning culinary creations", items: ["Sushi mosaic", "Vegetable carved sculptures", "Colorful molded desserts", "Painted chocolate art", "Molecular gastronomy bites"] },
        { id: 2, name: "Immersive Dining", price: 3500, description: "Multi-sensory food experience", items: ["Levitating appetizers", "Smoke-infused dishes", "LED-lit desserts", "Edible perfume pairings", "3D-printed food items"] },
      ],
      description: "Culinary Canvas turns food into art, creating visually spectacular dishes that are as beautiful as they are delicious.",
      staff: ["Food Artist", "Molecular Gastronomist", "Visual Design Expert"],
    },
  ],
  hennaArtists: [
    {
      id: 1,
      name: "Mehendi Magic",
      images: ["/henna-artists/mehendi-magic-1.jpg", "/henna-artists/mehendi-magic-2.jpg"],
      location: "Lahore",
      rating: 4.9,
      reviews: [],
      price: 15000,
      type: "Traditional",
      amenities: ["Natural Henna", "Bridal Package", "Touch-up Kit"],
      sponsored: true,
      packages: [
        { id: 1, name: "Bridal Bliss", price: 15000, description: "Intricate bridal henna for hands and feet", items: ["Full bridal henna", "Henna touch-up kit"] },
        { id: 2, name: "Mehendi Party", price: 25000, description: "Henna for bride and guests", items: ["Bridal henna", "Henna for 10 guests", "Henna care kit"] },
      ],
      description: "Mehendi Magic specializes in intricate henna designs for brides and wedding parties.",
      staff: ["Lead Henna Artist", "Assistant Henna Artist"],
    },
  ],
  weddingStationery: [],
  bridalWear: [],
  carRental: [],
}

