/**
 * Trade-operations config — the data that drives the generic per-trade operations
 * editor (components/.../trade-operations-hub-view.tsx). Each trade maps to one
 * function-sheet JSON column ("jsonField") whose value is { [section.key]: Row[] }.
 * One generic renderer + this registry = every trade's operational editor, with
 * no per-trade component. Photography keeps its own bespoke editor (two JSON
 * fields); these 9 single-field trades live here.
 *
 * The TRADE_OPS array is generated by the `trade-ops-schemas` workflow (one agent
 * per trade) and pasted in below.
 */

import type { IconName } from "@/components/dashboard/shared/icon"

export type TradeOpsColumnType = "text" | "number" | "date" | "select"

export interface TradeOpsColumn {
  key: string
  label: string
  type: TradeOpsColumnType
  /** Desktop grid span 1–11 (the 12th column is the delete button). */
  span: number
  placeholder?: string
  /** Options for `type: "select"`. */
  options?: string[]
}

export interface TradeOpsSection {
  key: string
  label: string
  icon: IconName
  desc: string
  addLabel: string
  columns: TradeOpsColumn[]
}

export interface TradeOpsTrade {
  /** Stable key + URL value (?trade=…). */
  trade: string
  label: string
  icon: IconName
  /** The FunctionSheet JSON column this trade writes to. */
  jsonField: string
  sections: TradeOpsSection[]
}

// Populated from the trade-ops-schemas workflow output.
export const TRADE_OPS: TradeOpsTrade[] = [
  {
    "trade": "beo",
    "label": "Run sheet",
    "icon": "ClipboardList",
    "jsonField": "beoJson",
    "sections": [
      {
        "key": "eventSpaces",
        "label": "Spaces & headcount",
        "icon": "MapPin",
        "desc": "Halls, lawns and stage areas in use with their expected covers and seating layout.",
        "addLabel": "Add space",
        "columns": [
          {
            "key": "spaceName",
            "label": "Space / area",
            "type": "text",
            "span": 4,
            "placeholder": "Shadi Hall, Main Lawn, Nikah Room"
          },
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 3,
            "options": [
              "Mayun",
              "Mehndi",
              "Nikah",
              "Baraat",
              "Walima",
              "Rukhsati",
              "Qawwali Night"
            ]
          },
          {
            "key": "layout",
            "label": "Layout",
            "type": "select",
            "span": 2,
            "options": [
              "Round tables",
              "Theatre / sofas",
              "Long banquet",
              "Floor seating (dholki)",
              "Standing / buffet",
              "Mixed"
            ]
          },
          {
            "key": "pax",
            "label": "Pax",
            "type": "number",
            "span": 2,
            "placeholder": "350"
          }
        ]
      },
      {
        "key": "timeline",
        "label": "Run of show",
        "icon": "Clock",
        "desc": "Minute-by-minute cue sheet from guest entry through baraat, dinner, stage and rukhsati.",
        "addLabel": "Add cue",
        "columns": [
          {
            "key": "cue",
            "label": "Cue / moment",
            "type": "text",
            "span": 4,
            "placeholder": "Baraat entry with dhol, stage flower shower"
          },
          {
            "key": "startTime",
            "label": "Time",
            "type": "text",
            "span": 2,
            "placeholder": "8:30 PM"
          },
          {
            "key": "segment",
            "label": "Segment",
            "type": "select",
            "span": 3,
            "options": [
              "Guest arrival",
              "Baraat entry",
              "Stage / jaimala",
              "Nikah",
              "Dinner service",
              "Cake cutting",
              "Qawwali / dance",
              "Dua",
              "Rukhsati",
              "Vendor teardown"
            ]
          },
          {
            "key": "owner",
            "label": "Cue caller",
            "type": "select",
            "span": 2,
            "options": [
              "Event manager",
              "Banquet captain",
              "MC / compere",
              "DJ / sound",
              "Caterer",
              "Decor lead",
              "Photographer",
              "Family coordinator"
            ]
          }
        ]
      },
      {
        "key": "setupTeardown",
        "label": "Setup & teardown",
        "icon": "CheckSquare",
        "desc": "Pre-event setup and post-rukhsati strike tasks with owners and ready-by deadlines.",
        "addLabel": "Add task",
        "columns": [
          {
            "key": "task",
            "label": "Task",
            "type": "text",
            "span": 4,
            "placeholder": "Stage flowers up, sound check, buffet chafing dishes hot"
          },
          {
            "key": "phase",
            "label": "Phase",
            "type": "select",
            "span": 2,
            "options": [
              "Setup",
              "During event",
              "Teardown"
            ]
          },
          {
            "key": "owner",
            "label": "Owner",
            "type": "select",
            "span": 3,
            "options": [
              "Venue ops",
              "Decor team",
              "Caterer",
              "Sound / DJ",
              "Lighting",
              "Security",
              "Valet",
              "Cleaning crew"
            ]
          },
          {
            "key": "readyBy",
            "label": "Ready by",
            "type": "text",
            "span": 2,
            "placeholder": "6:00 PM"
          }
        ]
      },
      {
        "key": "crewContacts",
        "label": "Crew & contacts",
        "icon": "Users",
        "desc": "Key on-site crew, vendor leads and family point-people with live phone numbers.",
        "addLabel": "Add contact",
        "columns": [
          {
            "key": "name",
            "label": "Name",
            "type": "text",
            "span": 4,
            "placeholder": "Bilal Ahmed"
          },
          {
            "key": "role",
            "label": "Role",
            "type": "select",
            "span": 3,
            "options": [
              "Event manager",
              "Banquet captain",
              "Caterer",
              "Decor lead",
              "Sound / DJ",
              "Photographer",
              "Security head",
              "Valet lead",
              "Bride's family",
              "Groom's family"
            ]
          },
          {
            "key": "phone",
            "label": "Phone",
            "type": "text",
            "span": 4,
            "placeholder": "0300-1234567"
          }
        ]
      }
    ]
  },
  {
    "trade": "kitchen",
    "label": "Kitchen sheet",
    "icon": "Utensils",
    "jsonField": "kitchenSheetJson",
    "sections": [
      {
        "key": "headcount",
        "label": "Headcount & function",
        "icon": "Users2",
        "desc": "Guaranteed vs expected covers per wedding function so the kitchen cooks to the right number.",
        "addLabel": "Add function",
        "columns": [
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 3,
            "options": [
              "Mayun",
              "Mehndi",
              "Dholki",
              "Baraat",
              "Nikah",
              "Walima",
              "Rukhsati",
              "Qawwali Night"
            ]
          },
          {
            "key": "guaranteedPax",
            "label": "Guaranteed pax",
            "type": "number",
            "span": 2,
            "placeholder": "350"
          },
          {
            "key": "expectedPax",
            "label": "Expected pax",
            "type": "number",
            "span": 2,
            "placeholder": "400"
          },
          {
            "key": "serviceStyle",
            "label": "Service style",
            "type": "select",
            "span": 2,
            "options": [
              "Buffet",
              "Sit-down / served",
              "Family style",
              "Live stalls only",
              "Boxed / takeaway"
            ]
          },
          {
            "key": "seating",
            "label": "Seating",
            "type": "select",
            "span": 2,
            "options": [
              "Mixed",
              "Segregated (separate halls)",
              "Ladies + Gents partitioned"
            ]
          }
        ]
      },
      {
        "key": "menuItems",
        "label": "Menu plan",
        "icon": "Utensils",
        "desc": "Every dish to be cooked with its category, per-head portion and dietary handling.",
        "addLabel": "Add dish",
        "columns": [
          {
            "key": "dish",
            "label": "Dish",
            "type": "text",
            "span": 4,
            "placeholder": "Chicken Biryani / Mutton Karahi"
          },
          {
            "key": "category",
            "label": "Category",
            "type": "select",
            "span": 2,
            "options": [
              "Rice / Biryani",
              "BBQ",
              "Handi / Salan",
              "Karahi",
              "Naan / Roti",
              "Daig / Pulao",
              "Salad / Raita",
              "Dessert / Sweet",
              "Chaat / Snacks",
              "Beverages"
            ]
          },
          {
            "key": "perHeadQty",
            "label": "Per head",
            "type": "text",
            "span": 2,
            "placeholder": "250g / 1 pc"
          },
          {
            "key": "dietary",
            "label": "Dietary",
            "type": "select",
            "span": 3,
            "options": [
              "Halal (standard)",
              "Vegetarian",
              "Vegan",
              "Jain (no onion/garlic)",
              "No beef",
              "Mild / no chillies",
              "Allergen-safe"
            ]
          }
        ]
      },
      {
        "key": "prepTimeline",
        "label": "Prep & cooking timeline",
        "icon": "Clock",
        "desc": "Degh-by-degh schedule for prep, cooking start and hot-hold-ready so food lands fresh at service.",
        "addLabel": "Add task",
        "columns": [
          {
            "key": "task",
            "label": "Task",
            "type": "text",
            "span": 4,
            "placeholder": "Marinate mutton / Light the deghs"
          },
          {
            "key": "stage",
            "label": "Stage",
            "type": "select",
            "span": 2,
            "options": [
              "Mise en place",
              "Marination",
              "Cooking",
              "Frying / BBQ",
              "Plating / Garnish",
              "Hot hold",
              "Service ready"
            ]
          },
          {
            "key": "startTime",
            "label": "Start",
            "type": "text",
            "span": 2,
            "placeholder": "2:00 PM"
          },
          {
            "key": "owner",
            "label": "Owner",
            "type": "text",
            "span": 2,
            "placeholder": "Head bawarchi"
          }
        ]
      },
      {
        "key": "stations",
        "label": "Live counters & stalls",
        "icon": "Truck",
        "desc": "Live-cooking stations and food stalls with their location and assigned staff for the floor.",
        "addLabel": "Add stall",
        "columns": [
          {
            "key": "stall",
            "label": "Stall / counter",
            "type": "text",
            "span": 3,
            "placeholder": "Chaat counter / Live BBQ"
          },
          {
            "key": "stationType",
            "label": "Type",
            "type": "select",
            "span": 2,
            "options": [
              "Live BBQ / Tikka",
              "Chaat / Gol Gappay",
              "Tawa / Paratha",
              "Dessert / Kulfi",
              "Tea / Kashmiri Chai",
              "Pan / Mukhwas",
              "Chinese / Continental",
              "Juice / Mocktail"
            ]
          },
          {
            "key": "location",
            "label": "Location",
            "type": "text",
            "span": 2,
            "placeholder": "Lawn entrance"
          },
          {
            "key": "staffCount",
            "label": "Staff",
            "type": "number",
            "span": 2,
            "placeholder": "3"
          },
          {
            "key": "incharge",
            "label": "Incharge",
            "type": "text",
            "span": 2,
            "placeholder": "Stall lead name"
          }
        ]
      }
    ]
  },
  {
    "trade": "bridal",
    "label": "Bridal Wear",
    "icon": "Sparkles",
    "jsonField": "bridalWearJson",
    "sections": [
      {
        "key": "functionOutfits",
        "label": "Outfits by Function",
        "icon": "Sparkles",
        "desc": "One bridal outfit per wedding function with fabric, colour and designer.",
        "addLabel": "Add outfit",
        "columns": [
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 2,
            "options": [
              "Mayun",
              "Dholki",
              "Mehndi",
              "Baraat / Nikah",
              "Rukhsati",
              "Walima",
              "Valima Reception"
            ]
          },
          {
            "key": "outfitType",
            "label": "Outfit",
            "type": "select",
            "span": 2,
            "options": [
              "Lehenga",
              "Sharara",
              "Gharara",
              "Anarkali / Pishwas",
              "Maxi / Gown",
              "Saree",
              "Angrakha",
              "Farshi Pajama"
            ]
          },
          {
            "key": "fabricColour",
            "label": "Fabric & Colour",
            "type": "text",
            "span": 3,
            "placeholder": "e.g. Red velvet with gold zardozi"
          },
          {
            "key": "designer",
            "label": "Designer / Source",
            "type": "text",
            "span": 2,
            "placeholder": "e.g. HSY, Maria B, custom darzi"
          },
          {
            "key": "status",
            "label": "Status",
            "type": "select",
            "span": 2,
            "options": [
              "Concept / Design",
              "Fabric Sourced",
              "Stitching",
              "Embroidery / Adda",
              "Ready for Fitting",
              "Finalised",
              "Delivered"
            ]
          }
        ]
      },
      {
        "key": "fittingSchedule",
        "label": "Fitting & Alteration Schedule",
        "icon": "CalendarClock",
        "desc": "Measurement, trial and alteration appointments for each outfit before its function.",
        "addLabel": "Add fitting",
        "columns": [
          {
            "key": "outfitFunction",
            "label": "Outfit / Function",
            "type": "select",
            "span": 3,
            "options": [
              "Mayun",
              "Mehndi",
              "Baraat / Nikah",
              "Rukhsati",
              "Walima",
              "All Outfits"
            ]
          },
          {
            "key": "appointmentType",
            "label": "Appointment",
            "type": "select",
            "span": 2,
            "options": [
              "Measurements Taken",
              "First Trial",
              "Second Trial",
              "Alteration",
              "Final Fitting",
              "Delivery Pickup"
            ]
          },
          {
            "key": "fittingDate",
            "label": "Date",
            "type": "date",
            "span": 2
          },
          {
            "key": "measurements",
            "label": "Measurements / Alteration Notes",
            "type": "text",
            "span": 3,
            "placeholder": "e.g. Bust 36, take in waist 2in, blouse length +1in"
          },
          {
            "key": "fittingStatus",
            "label": "Status",
            "type": "select",
            "span": 1,
            "options": [
              "Pending",
              "Booked",
              "Done",
              "Redo"
            ]
          }
        ]
      },
      {
        "key": "accessoriesChecklist",
        "label": "Accessories & Jewellery",
        "icon": "ClipboardList",
        "desc": "Jewellery, dupatta-setting and accessory items with delivery dates per function.",
        "addLabel": "Add accessory",
        "columns": [
          {
            "key": "item",
            "label": "Item",
            "type": "text",
            "span": 3,
            "placeholder": "e.g. Polki maatha patti, kaleere, jhumar"
          },
          {
            "key": "category",
            "label": "Category",
            "type": "select",
            "span": 2,
            "options": [
              "Jewellery Set",
              "Maatha Patti / Tikka",
              "Jhumar / Passa",
              "Nath",
              "Bangles / Chooriyan",
              "Kaleere",
              "Dupatta / Veil",
              "Khussa / Footwear",
              "Clutch / Purse",
              "Hair / Accessories"
            ]
          },
          {
            "key": "forFunction",
            "label": "For Function",
            "type": "select",
            "span": 2,
            "options": [
              "Mayun",
              "Mehndi",
              "Baraat / Nikah",
              "Rukhsati",
              "Walima"
            ]
          },
          {
            "key": "deliveryDate",
            "label": "Delivery Date",
            "type": "date",
            "span": 2
          },
          {
            "key": "itemStatus",
            "label": "Status",
            "type": "select",
            "span": 2,
            "options": [
              "To Order",
              "Ordered",
              "On Rent",
              "Received",
              "Delivered to Bride",
              "Returned"
            ]
          }
        ]
      }
    ]
  },
  {
    "trade": "decorator",
    "label": "Decor setup",
    "icon": "Sparkles",
    "jsonField": "decoratorSetupJson",
    "sections": [
      {
        "key": "setupItems",
        "label": "Setup item list",
        "icon": "Package",
        "desc": "Every decor element to install for this function, with quantity and the area it covers.",
        "addLabel": "Add item",
        "columns": [
          {
            "key": "itemName",
            "label": "Item / element",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Main stage backdrop, jhula, entrance gate"
          },
          {
            "key": "category",
            "label": "Category",
            "type": "select",
            "span": 3,
            "options": [
              "Stage & backdrop",
              "Floral & jaimala",
              "Lighting & fairy lights",
              "Furniture & seating",
              "Drapes & ceiling",
              "Entrance & walkway",
              "Centerpieces & table",
              "Props & signage"
            ]
          },
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 2,
            "options": [
              "Mayun",
              "Mehndi",
              "Baraat",
              "Walima",
              "Rukhsati",
              "Nikah",
              "Qawwali night"
            ]
          },
          {
            "key": "quantity",
            "label": "Qty",
            "type": "number",
            "span": 1,
            "placeholder": "1"
          },
          {
            "key": "area",
            "label": "Area / location",
            "type": "text",
            "span": 1,
            "placeholder": "Main hall"
          }
        ]
      },
      {
        "key": "installSchedule",
        "label": "Install & teardown schedule",
        "icon": "CalendarClock",
        "desc": "When each crew loads in, sets up, and strikes the decor around the function timing.",
        "addLabel": "Add task",
        "columns": [
          {
            "key": "task",
            "label": "Task",
            "type": "text",
            "span": 3,
            "placeholder": "e.g. Stage rigging, floral install, post-event strike"
          },
          {
            "key": "phase",
            "label": "Phase",
            "type": "select",
            "span": 2,
            "options": [
              "Load-in",
              "Setup",
              "Final touch-up",
              "Live standby",
              "Teardown / strike",
              "Load-out"
            ]
          },
          {
            "key": "scheduledDate",
            "label": "Date",
            "type": "date",
            "span": 2
          },
          {
            "key": "startTime",
            "label": "Start time",
            "type": "text",
            "span": 2,
            "placeholder": "e.g. 8:00 AM"
          },
          {
            "key": "crewLead",
            "label": "Crew lead",
            "type": "text",
            "span": 1,
            "placeholder": "Name"
          },
          {
            "key": "crewSize",
            "label": "Crew",
            "type": "number",
            "span": 1,
            "placeholder": "6"
          }
        ]
      },
      {
        "key": "themePalette",
        "label": "Theme & colour palette",
        "icon": "Image",
        "desc": "The agreed look for each function with reference notes the crew dresses to.",
        "addLabel": "Add theme",
        "columns": [
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 2,
            "options": [
              "Mayun",
              "Mehndi",
              "Baraat",
              "Walima",
              "Rukhsati",
              "Nikah",
              "Qawwali night"
            ]
          },
          {
            "key": "themeName",
            "label": "Theme / concept",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Mughal garden, royal maroon-gold, pastel floral"
          },
          {
            "key": "colourPalette",
            "label": "Colour palette",
            "type": "text",
            "span": 3,
            "placeholder": "e.g. Maroon, gold, ivory"
          },
          {
            "key": "referenceNotes",
            "label": "Reference notes",
            "type": "text",
            "span": 2,
            "placeholder": "Pinterest / sample link"
          }
        ]
      }
    ]
  },
  {
    "trade": "carRental",
    "label": "Fleet plan",
    "icon": "Truck",
    "jsonField": "carRentalJson",
    "sections": [
      {
        "key": "vehicles",
        "label": "Fleet & Vehicles",
        "icon": "Truck",
        "desc": "List every vehicle assigned to this wedding, with type, plate and decor.",
        "addLabel": "Add vehicle",
        "columns": [
          {
            "key": "vehicleName",
            "label": "Vehicle / Model",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Toyota Fortuner (white)"
          },
          {
            "key": "vehicleType",
            "label": "Type",
            "type": "select",
            "span": 3,
            "options": [
              "Luxury sedan (dulha car)",
              "Vintage / classic",
              "Coaster (baraatis)",
              "Hiace van",
              "Limousine",
              "SUV / 4x4",
              "Bridal car (decorated)",
              "Standard car"
            ]
          },
          {
            "key": "plateNumber",
            "label": "Plate No.",
            "type": "text",
            "span": 2,
            "placeholder": "LEA-1234"
          },
          {
            "key": "decor",
            "label": "Flower decor",
            "type": "select",
            "span": 2,
            "options": [
              "Full floral decor",
              "Light decor",
              "No decor"
            ]
          }
        ]
      },
      {
        "key": "routeSchedule",
        "label": "Pickup & Route Schedule",
        "icon": "MapPin",
        "desc": "Plan each pickup by function with time, pickup point and drop-off.",
        "addLabel": "Add route",
        "columns": [
          {
            "key": "pickupPoint",
            "label": "Pickup Point",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Dulha's house, DHA Phase 5"
          },
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 3,
            "options": [
              "Mayun",
              "Mehndi",
              "Baraat",
              "Rukhsati",
              "Walima",
              "Airport / guest pickup",
              "Other"
            ]
          },
          {
            "key": "pickupTime",
            "label": "Pickup Time",
            "type": "text",
            "span": 2,
            "placeholder": "4:30 PM"
          },
          {
            "key": "dropPoint",
            "label": "Drop-off",
            "type": "text",
            "span": 2,
            "placeholder": "Marquee / venue"
          }
        ]
      },
      {
        "key": "drivers",
        "label": "Driver Roster",
        "icon": "User",
        "desc": "Assign drivers with contact, vehicle and reporting time for the day.",
        "addLabel": "Add driver",
        "columns": [
          {
            "key": "driverName",
            "label": "Driver Name",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Akram Bhai"
          },
          {
            "key": "phone",
            "label": "Contact No.",
            "type": "text",
            "span": 3,
            "placeholder": "0300-1234567"
          },
          {
            "key": "assignedVehicle",
            "label": "Assigned Vehicle",
            "type": "text",
            "span": 2,
            "placeholder": "Plate / model"
          },
          {
            "key": "reportTime",
            "label": "Report Time",
            "type": "text",
            "span": 2,
            "placeholder": "3:00 PM"
          }
        ]
      }
    ]
  },
  {
    "trade": "henna",
    "label": "Mehndi plan",
    "icon": "Sparkles",
    "jsonField": "hennaJson",
    "sections": [
      {
        "key": "designList",
        "label": "Design List (Per Person)",
        "icon": "Heart",
        "desc": "Who is getting henna applied, in what style and how detailed the work is.",
        "addLabel": "Add person",
        "columns": [
          {
            "key": "person",
            "label": "Person / Name",
            "type": "text",
            "span": 3,
            "placeholder": "Bride (Dulhan), Bride's mother, Guest..."
          },
          {
            "key": "coverage",
            "label": "Coverage",
            "type": "select",
            "span": 2,
            "options": [
              "Bridal full hands + feet",
              "Both hands (full)",
              "Both hands (half)",
              "One hand only",
              "Hands + feet",
              "Feet only",
              "Fingertips / minimal"
            ]
          },
          {
            "key": "style",
            "label": "Style",
            "type": "select",
            "span": 2,
            "options": [
              "Pakistani",
              "Indian",
              "Arabic",
              "Indo-Arabic fusion",
              "Khaleeji / Gulf",
              "Moroccan",
              "Minimal / Modern"
            ]
          },
          {
            "key": "complexity",
            "label": "Complexity",
            "type": "select",
            "span": 2,
            "options": [
              "Bridal intricate",
              "Heavy / detailed",
              "Medium",
              "Light / simple"
            ]
          },
          {
            "key": "qty",
            "label": "Qty",
            "type": "number",
            "span": 1,
            "placeholder": "1"
          }
        ]
      },
      {
        "key": "artistRoster",
        "label": "Artist Roster & Assignments",
        "icon": "Users2",
        "desc": "The henna artists working this job and what each one is responsible for.",
        "addLabel": "Add artist",
        "columns": [
          {
            "key": "artistName",
            "label": "Artist Name",
            "type": "text",
            "span": 3,
            "placeholder": "Lead artist / Apprentice name"
          },
          {
            "key": "role",
            "label": "Role",
            "type": "select",
            "span": 2,
            "options": [
              "Lead / Bridal specialist",
              "Senior artist",
              "Junior artist",
              "Apprentice",
              "Cone filler / Helper"
            ]
          },
          {
            "key": "assignment",
            "label": "Assigned To",
            "type": "select",
            "span": 3,
            "options": [
              "Bride (Dulhan)",
              "Bride's family",
              "Groom's family",
              "Guests queue",
              "Kids",
              "Floater / Backup"
            ]
          },
          {
            "key": "guestsTarget",
            "label": "Guests",
            "type": "number",
            "span": 1,
            "placeholder": "0"
          },
          {
            "key": "fee",
            "label": "Fee (Rs)",
            "type": "number",
            "span": 2,
            "placeholder": "0"
          }
        ]
      },
      {
        "key": "scheduleSlots",
        "label": "Schedule & Slots",
        "icon": "CalendarClock",
        "desc": "When and where each henna session happens across the wedding functions.",
        "addLabel": "Add slot",
        "columns": [
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 3,
            "options": [
              "Mayun",
              "Mehndi",
              "Dholki",
              "Baraat",
              "Walima",
              "Rukhsati",
              "Pre-wedding trial"
            ]
          },
          {
            "key": "date",
            "label": "Date",
            "type": "date",
            "span": 2
          },
          {
            "key": "startTime",
            "label": "Start Time",
            "type": "text",
            "span": 2,
            "placeholder": "e.g. 4:00 PM"
          },
          {
            "key": "venue",
            "label": "Venue / Location",
            "type": "text",
            "span": 3,
            "placeholder": "Home / Banquet / Marquee address"
          },
          {
            "key": "status",
            "label": "Status",
            "type": "select",
            "span": 1,
            "options": [
              "Planned",
              "Confirmed",
              "In progress",
              "Done"
            ]
          }
        ]
      }
    ]
  },
  {
    "trade": "stationery",
    "label": "Stationery",
    "icon": "FileText",
    "jsonField": "stationeryJson",
    "sections": [
      {
        "key": "itemList",
        "label": "Items & Stationery",
        "icon": "ClipboardList",
        "desc": "Every printed and crafted item for the wedding, with quantity and finish.",
        "addLabel": "Add item",
        "columns": [
          {
            "key": "itemName",
            "label": "Item",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Baraat invite card, mehndi favour box"
          },
          {
            "key": "category",
            "label": "Category",
            "type": "select",
            "span": 2,
            "options": [
              "Invite card",
              "Invite box",
              "Mehndi favour",
              "Menu card",
              "Signage / standee",
              "Tags & labels",
              "Thank-you card",
              "Envelope / insert"
            ]
          },
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 2,
            "options": [
              "Mayun",
              "Dholki",
              "Mehndi",
              "Baraat / Nikah",
              "Walima",
              "Rukhsati",
              "All functions"
            ]
          },
          {
            "key": "quantity",
            "label": "Qty",
            "type": "number",
            "span": 1,
            "placeholder": "250"
          },
          {
            "key": "finish",
            "label": "Finish",
            "type": "select",
            "span": 2,
            "options": [
              "Matte",
              "Gloss",
              "Gold foil",
              "Silver foil",
              "Embossed",
              "Laser-cut",
              "Velvet / suede",
              "Acrylic",
              "Handmade paper"
            ]
          }
        ]
      },
      {
        "key": "proofApprovals",
        "label": "Proof & Approval Tracker",
        "icon": "CheckSquare",
        "desc": "Design sign-off status for each item before it goes to print.",
        "addLabel": "Add proof",
        "columns": [
          {
            "key": "itemName",
            "label": "Item",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Baraat invite card"
          },
          {
            "key": "approver",
            "label": "Approver",
            "type": "select",
            "span": 2,
            "options": [
              "Bride",
              "Groom",
              "Bride's family",
              "Groom's family",
              "Wedding planner",
              "Event coordinator"
            ]
          },
          {
            "key": "status",
            "label": "Status",
            "type": "select",
            "span": 3,
            "options": [
              "Draft pending",
              "Proof sent",
              "Revision requested",
              "Approved",
              "Sent to print"
            ]
          },
          {
            "key": "approvedOn",
            "label": "Approved on",
            "type": "date",
            "span": 2
          }
        ]
      },
      {
        "key": "printDelivery",
        "label": "Print & Delivery Schedule",
        "icon": "Truck",
        "desc": "Press dates, dispatch and where each batch is delivered before the function.",
        "addLabel": "Add delivery",
        "columns": [
          {
            "key": "itemName",
            "label": "Item",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Mehndi favour boxes"
          },
          {
            "key": "stage",
            "label": "Stage",
            "type": "select",
            "span": 3,
            "options": [
              "At press",
              "Printed",
              "Assembly / packing",
              "Out for delivery",
              "Delivered",
              "Handed to client"
            ]
          },
          {
            "key": "deliverTo",
            "label": "Deliver to",
            "type": "select",
            "span": 2,
            "options": [
              "Bride's home",
              "Groom's home",
              "Banquet / hall",
              "Marquee",
              "Planner's office",
              "Courier (TCS / Leopards)"
            ]
          },
          {
            "key": "deliveryDate",
            "label": "Delivery date",
            "type": "date",
            "span": 2
          }
        ]
      }
    ]
  },
  {
    "trade": "makeup",
    "label": "Makeup plan",
    "icon": "Sparkles",
    "jsonField": "makeupJson",
    "sections": [
      {
        "key": "functionLooks",
        "label": "Bridal Looks per Function",
        "icon": "Heart",
        "desc": "Plan the bride's look for each wedding function with style direction.",
        "addLabel": "Add look",
        "columns": [
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 2,
            "options": [
              "Mayun",
              "Dholki",
              "Mehndi",
              "Baraat / Nikah",
              "Rukhsati",
              "Walima",
              "Reception"
            ]
          },
          {
            "key": "lookStyle",
            "label": "Look & Style Notes",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. soft glam, dewy base, golden smokey eye, red lip"
          },
          {
            "key": "coverage",
            "label": "Makeup Type",
            "type": "select",
            "span": 2,
            "options": [
              "HD Makeup",
              "Airbrush",
              "Matte / Traditional",
              "Natural / Soft Glam",
              "Full Glam"
            ]
          },
          {
            "key": "hairstyle",
            "label": "Hair & Dupatta Set",
            "type": "text",
            "span": 3,
            "placeholder": "e.g. side bun, front dupatta pin, jhoomar setting"
          }
        ]
      },
      {
        "key": "trialSchedule",
        "label": "Trial Schedule",
        "icon": "CalendarCheck",
        "desc": "Track pre-wedding makeup trials and the bride's sign-off.",
        "addLabel": "Add trial",
        "columns": [
          {
            "key": "trialFor",
            "label": "Trial For",
            "type": "select",
            "span": 3,
            "options": [
              "Mehndi Look",
              "Baraat / Nikah Look",
              "Walima Look",
              "Engagement",
              "General / First Trial"
            ]
          },
          {
            "key": "trialDate",
            "label": "Trial Date",
            "type": "date",
            "span": 2
          },
          {
            "key": "venue",
            "label": "Venue / Studio",
            "type": "text",
            "span": 3,
            "placeholder": "e.g. salon, bride's home"
          },
          {
            "key": "status",
            "label": "Status",
            "type": "select",
            "span": 3,
            "options": [
              "Scheduled",
              "Done - Approved",
              "Done - Needs Changes",
              "Rescheduled",
              "Cancelled"
            ]
          }
        ]
      },
      {
        "key": "kitChecklist",
        "label": "Product & Kit Checklist",
        "icon": "ShoppingBag",
        "desc": "Confirm products and tools are stocked and packed before the event.",
        "addLabel": "Add product",
        "columns": [
          {
            "key": "item",
            "label": "Product / Item",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. foundation shade, false lashes, setting spray"
          },
          {
            "key": "category",
            "label": "Category",
            "type": "select",
            "span": 3,
            "options": [
              "Base / Foundation",
              "Eyes",
              "Lips & Cheeks",
              "Lashes & Brows",
              "Setting & Finish",
              "Skin Prep",
              "Tools / Brushes",
              "Hair & Setting"
            ]
          },
          {
            "key": "qty",
            "label": "Qty",
            "type": "number",
            "span": 1
          },
          {
            "key": "status",
            "label": "Stock Status",
            "type": "select",
            "span": 3,
            "options": [
              "In Kit - Packed",
              "Available",
              "Low - Reorder",
              "Out of Stock",
              "To Purchase"
            ]
          }
        ]
      },
      {
        "key": "dayOfTiming",
        "label": "Day-of Timing & Artist Assignment",
        "icon": "Clock",
        "desc": "Sequence the day-of schedule and assign artists to the bride and party.",
        "addLabel": "Add slot",
        "columns": [
          {
            "key": "client",
            "label": "Client / Person",
            "type": "text",
            "span": 3,
            "placeholder": "e.g. Bride, bride's mother, sister, friend"
          },
          {
            "key": "service",
            "label": "Service",
            "type": "select",
            "span": 2,
            "options": [
              "Bridal Makeup",
              "Party / Family Makeup",
              "Hair Only",
              "Dupatta Setting",
              "Touch-up",
              "Saheli Package"
            ]
          },
          {
            "key": "startTime",
            "label": "Start Time",
            "type": "text",
            "span": 2,
            "placeholder": "e.g. 2:00 PM"
          },
          {
            "key": "artist",
            "label": "Assigned Artist",
            "type": "text",
            "span": 2,
            "placeholder": "lead / assistant name"
          },
          {
            "key": "status",
            "label": "Status",
            "type": "select",
            "span": 2,
            "options": [
              "Pending",
              "In Progress",
              "Done",
              "Running Late"
            ]
          }
        ]
      }
    ]
  },
  {
    "trade": "subcontracts",
    "label": "Subcontracts",
    "icon": "Users2",
    "jsonField": "subcontractsJson",
    "sections": [
      {
        "key": "subcontractors",
        "label": "Subcontractor Roster",
        "icon": "Users2",
        "desc": "List every vendor you have outsourced part of this job to, with their scope and contact.",
        "addLabel": "Add subcontractor",
        "columns": [
          {
            "key": "vendorName",
            "label": "Vendor / Firm Name",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Lahore Dhol Group, Al-Madina Caterers"
          },
          {
            "key": "scope",
            "label": "Service / Scope",
            "type": "select",
            "span": 3,
            "options": [
              "Catering",
              "BBQ & Handi Stall",
              "Dhol & Band Baja",
              "DJ & Sound",
              "Stage & Decor",
              "Floral / Phool",
              "Lighting & Truss",
              "Photography",
              "Videography & Drone",
              "Mehndi Setup",
              "Mehndi Artist",
              "Makeup Artist",
              "Sehra Bandi",
              "Car Decoration",
              "Horse / Baggi",
              "Fireworks / Aatishbazi",
              "Valet & Parking",
              "Generator / Power",
              "Tent & Marquee",
              "Furniture Rental",
              "Waiters / Service Staff",
              "Security Guards",
              "Transport / Coaster",
              "Sound for Nikkah"
            ]
          },
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 2,
            "options": [
              "Mayun",
              "Dholki",
              "Mehndi",
              "Baraat",
              "Nikkah",
              "Rukhsati",
              "Walima",
              "Qawwali Night",
              "All Functions"
            ]
          },
          {
            "key": "contactNumber",
            "label": "Contact No.",
            "type": "text",
            "span": 2,
            "placeholder": "03xx-xxxxxxx"
          }
        ]
      },
      {
        "key": "costPayments",
        "label": "Cost & Payment Status",
        "icon": "Wallet",
        "desc": "Track what each subcontractor is owed, what has been paid, and the settlement status.",
        "addLabel": "Add payment",
        "columns": [
          {
            "key": "vendorName",
            "label": "Subcontractor",
            "type": "text",
            "span": 3,
            "placeholder": "Match roster vendor name"
          },
          {
            "key": "agreedCost",
            "label": "Agreed Cost (Rs)",
            "type": "number",
            "span": 2,
            "placeholder": "0"
          },
          {
            "key": "advancePaid",
            "label": "Advance Paid (Rs)",
            "type": "number",
            "span": 2,
            "placeholder": "0"
          },
          {
            "key": "paymentStatus",
            "label": "Status",
            "type": "select",
            "span": 2,
            "options": [
              "Quote Pending",
              "Advance Paid",
              "Partially Paid",
              "Paid in Full",
              "Payment On Event Day",
              "Held / Disputed",
              "Cancelled"
            ]
          },
          {
            "key": "paymentMode",
            "label": "Mode",
            "type": "select",
            "span": 2,
            "options": [
              "Cash",
              "Bank Transfer",
              "JazzCash",
              "Easypaisa",
              "Cheque",
              "On Delivery"
            ]
          }
        ]
      },
      {
        "key": "deliverableHandover",
        "label": "Deliverable & Handover Schedule",
        "icon": "Truck",
        "desc": "When each subcontractor must deliver, set up, or hand over on event day, and the on-ground state.",
        "addLabel": "Add handover",
        "columns": [
          {
            "key": "deliverable",
            "label": "Deliverable / Handover",
            "type": "text",
            "span": 4,
            "placeholder": "e.g. Stage ready, Biryani degs delivered, Edited photos"
          },
          {
            "key": "function",
            "label": "Function",
            "type": "select",
            "span": 2,
            "options": [
              "Mayun",
              "Dholki",
              "Mehndi",
              "Baraat",
              "Nikkah",
              "Rukhsati",
              "Walima",
              "Qawwali Night"
            ]
          },
          {
            "key": "dueDate",
            "label": "Due / Setup Date",
            "type": "date",
            "span": 2
          },
          {
            "key": "readyByTime",
            "label": "Ready By",
            "type": "text",
            "span": 1,
            "placeholder": "06:00 PM"
          },
          {
            "key": "handoverStatus",
            "label": "Status",
            "type": "select",
            "span": 2,
            "options": [
              "Not Started",
              "In Progress",
              "On Site",
              "Setup Done",
              "Delivered",
              "Delayed",
              "Issue Reported"
            ]
          }
        ]
      }
    ]
  }
]

export const getTrade = (key?: string | null): TradeOpsTrade | undefined =>
  TRADE_OPS.find((t) => t.trade === key) ?? TRADE_OPS[0]
