/**
 * The hero photographs, as pre-generated AVIF rather than /_next/image URLs.
 *
 * The Vercel image-optimization quota is exhausted, and it fails silently: a
 * variant already in its cache returns 200, any variant that is not returns 402.
 * The homepage hero was rendering only because `w=1200&q=75` happened to be
 * cached — one eviction from breaking the largest paint on the busiest page, and
 * impossible to tune, because changing the quality by one point makes a new
 * variant and a new variant 402s.
 *
 * These are static files under /public, built by
 * scripts/build/gen-hero-images.cjs. No optimizer, no quota, no `dpl` token —
 * which also means a preload link can be written by hand and will keep matching
 * across deploys, which was not true of an /_next/image URL.
 */

/** Widths generated by scripts/build/gen-hero-images.cjs. */
export const HERO_WIDTHS = [828, 1200, 1920] as const

const BASES = ["spotlight", "h2", "h3", "h4", "venue", "h6", "h7"] as const

export const HERO_SLIDES = BASES.map((base) => ({
  base,
  src: `/images/home/hero-opt/${base}-1200.avif`,
  srcSet: HERO_WIDTHS.map((w) => `/images/home/hero-opt/${base}-${w}.avif ${w}w`).join(", "),
}))
